# Generated by Django 6.1.1 on 2026-09-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_batch_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='form',
            field=models.CharField(blank=True, choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('ointment', 'Ointment')], max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='medicine',
            constraint=models.UniqueConstraint(fields=('name', 'form', 'strength'), name='unique_medicine'),
        ),
    ]
