# Generated by Django 6.1.1 on 2026-09-30 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_batch_form_medicine_unique_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='form',
        ),
    ]
