# Generated by Django 6.1.1 on 2026-10-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_batch_medicine_alter_medicine_category'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='batch',
            name='unique_medicine_batch',
        ),
        migrations.AddField(
            model_name='batch',
            name='form',
            field=models.CharField(blank=True, choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('syrup', 'Syrup'), ('injection', 'Injection'), ('ointment', 'Ointment')], max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('medicine', 'batch_number', 'form'), name='unique_medicine_batch'),
        ),
    ]
