# Generated by Django 6.1.1 on 2026-10-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_remove_batch_unique_medicine_batch_batch_form_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='batch',
            name='unique_medicine_batch',
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.UniqueConstraint(fields=('medicine', 'batch_number'), name='unique_medicine_batch'),
        ),
        migrations.RemoveField(
            model_name='batch',
            name='form',
        ),
    ]
