# Generated by Django 6.1.1 on 2026-10-03 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_patient_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contact_number',
            field=models.CharField(blank=True, db_index=True, help_text="'03XXXXXXXXX' or '+923XXXXXXXXX'", max_length=14, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+923XXXXXXXXX' or '03XXXXXXXXX'.", regex='^(?:\\+92|0092|92|0)?(?:3[0-7]\\d{1})\\s?-?\\d{7}$')]),
        ),
    ]
